version: "3"
services:
  httpd:
    build:
      context: .
      dockerfile: httpd.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./logs/httpd:/logs

  phpfpm:
    build:
      context: .
      dockerfile: php.Dockerfile
    expose:
      - 9000
    volumes:
      - ./www:/var/www/html

  db:
    image: mysql:8.0.16
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - 81:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

  adminer:
    image: adminer:4.8.0-standalone
    ports:
      - 82:8080
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test


volumes:
    persistent: