version: "3"
services:
  httpd:
    build:
      context: .
      dockerfile: httpd.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./logs/httpd:/logs

  phpfpm:
    build:
      context: .
      dockerfile: php.Dockerfile
      args: 
        - PHP_VERSION=${PHP_VERSION:-7.3} # eg : 7.3.27-fpm-alpine or better for CmsMadeSimple 2.2.15
    expose:
      - 9000
    volumes:
      - ./www:/var/www/html
      - ./logs/php:/var/log/

  db:
    image: mysql:${MYSQL_VERSION:-5.5} # eg : 5.5.62 or better for CmsMadeSimple 2.2.15
    #If MYSQL_VERSION > 8.0.0
    #command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    #If MYSQL_VERSION < 8.0.0
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-myDb}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-test}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-test}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - 81:80

  adminer:
    image: adminer:4.8.0-standalone
    ports:
      - 82:8080


volumes:
    persistent: